name:                zeromq4-simple
version:             0.0.0
github:              "athanclark/zeromq4-simple"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "2018, 2019 (c) Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            More constrained extensions to zeromq4-haskell
category:            System, FFI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/athanclark/zeromq4-simple#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- constraints
- hashable
- uuid
- zeromq4-haskell

library:
  source-dirs: src
